# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Simvue Client (Ubuntu)

on:
  push:
    branches: ["main", "dev", "hotfix/update-ci"]
  pull_request:
    branches: [ "main", "dev", "hotfix/update-ci" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Setup Eco Measure
      uses: green-coding-solutions/eco-ci-energy-estimation@v4.0-rc3
      with:
        task: start-measurement
    - name: Install dependencies
      run: python -m pip install poetry
    - name: Test with pytest
      run: |
        export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
        export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
        poetry install --all-extras
        poetry run python -m pip install torch --index-url https://download.pytorch.org/whl/cpu
        poetry run pytest -x --cov --cov-report=xml tests/unit/ tests/refactor/ -m 'not scenario'
    - name: Retrieve Eco Measure
      uses: green-coding-solutions/eco-ci-energy-estimation@v4.0-rc3
      with:
        task: get-measurement
        label: "test execution"
    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
    - name: Display Test Eco Measure
      uses: green-coding-solutions/eco-ci-energy-estimation@v4.0-rc3
      with:
        task: display-results
